### ISSUE TITLE
My own version of the placer

### ISSUE THREAD

**Issue by zykrah** [adamws/kicad-kbplacer#1]
Just thought I'd mention and bring light to my take on this plugin [here](https://github.com/zykrah/kicad-kle-placer).

It removes the need for a kle-serial compatible json. It has it's own serializer/deserializer code. There's also some stuff which lets you customize rotations, do multi-layout, support more complicated layouts with rotation, and also specify diode location.

Disclaimer, I did use a lot of the logic from this project while I was making it (yours wasn't updated to V6 at the time).

(If this interests you, I also have [this](https://github.com/zykrah/firmware-scripts), which is where the serialization code first came from)

**Comment by adamws** [comment]
> It removes the need for a kle-serial compatible json. It has it's own serializer/deserializer code. 

back when I started this project I was also considering writing my own de-serialized and decided against it. It was less work and in theory this plugin will be still compatible with keyboard-layout-editor if it changes internal representation.

I admit it is a bit inconvenient for user and since ijprest's project are pretty much dead at this point it perhaps makes more sense to have own implementation.

In the other hand I do have converter hosted here: http://keyboard-tools.xyz/kle-converter
so this conversion shouldn't be that difficult for the user. Maybe supporting both formats would be the best option.

> There's also some stuff which lets you customize rotations, do multi-layout, support more complicated layouts with rotation

nice :+1:

> and also specify diode location

this feature is on my todo since day one. I like your approach of using first switch/diode as reference for placement.

This project was on hold for a long time but it gained my attention recently. I added v6 compatibility and submitted it to official kicad's plugin repository. I plan to continue implementing new stuff at my own pace but I'm open to contributions.
